NIE/CSE/urls.py
from django.urls import path
 from CSE.views import StuList,Forms, StudentDetail, StudentUpdate, StudentDelete


app_name = 'CSE'
urlpatterns = [
 path('index', views.index, name = 'index'),
path('products', views.products, name = 'products'),
path('service', views.service, name = 'service'),
path('contacts', views.contacts, name = 'contacts'),
path('basic', views.basic, name = 'basic'),
path('studentList', views.studentList, name = 'studentList'),


path('', StuList.as_view(), name = 'list'),
path('forms', Forms.as_view(), name = 'forms'),
path('<pk>/detail', StudentDetail.as_view(), name = 'detail'),
path('<pk>/update', StudentUpdate.as_view(), name = 'update'),
path('<pk>/delete', StudentDelete.as_view(), name = 'delete'),
]

NIE/NIE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CSE.urls')),
]

NIE/CSE/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=30)
    college_name = models.CharField(max_length=30)
    rollnumber = models.IntegerField()
    def __str__(self):
        return self.name

NIE/CSE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def products(request):
    name = 'raju'
    department = 'CSE'
    college_name = 'NIE'
    roll_number = 60145
    context = {'name': name, 'c_name': college_name, 'd_name': department, 'r_number':roll_number}
    return render(request,'products.html',  context)

def service(request):
    return render(request,'service.html')

def contacts(request):
    return render(request,'contacts.html')

def studentList(request):
    return render(request,'studentList.html')


def basic(request):
    return render(request,'basic.html')


 #FBV - List view
from CSE.models import Student
def studentList(request):
    students = Student.objects.all()
    context ={'students':students}
    return render(request, 'studentList.html', context)

#FBV 
from CSE.models import Student
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

class StuList(ListView):
    model = Student
    template_name = 'CBV/list.html'


class Forms(CreateView):
    model = Student
    fields = "__all__"
    template_name = 'CBV/forms.html'
    success_url = '/'


class StudentDetail(DetailView):
    model = Student
    template_name = 'CBV/detail.html'

class StudentUpdate(UpdateView):
    model = Student
    fields = '__all__'
    template_name = 'CBV/update.html'
    success_url = '/'

class StudentDelete(DeleteView):
    model = Student
    template_name = 'CBV/delete.html'
    success_url = '/'

NIE/templates/CBV/delete.html

{% extends 'basic.html' %}

{% block content %}
<h1>Student Delete page.</h1>
<form method="post">
    {% csrf_token %} <br><br><br>
    <h1>    Are you sure you want to delete "{{ object }}"? </h1>
      <br><br><br><br>

    <table class="table table-striped table-bordered table-hover table-condensed">
    <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Department</th>
            <th scope="col">Roll number</th>
            <th scope="col">College Name</th>
            <th scope="col">ID</th>
            
          </tr>
        </thead>
        <tbody>
           
          <tr>
            
            <td>{{object.name}}</td>
            <td>{{object.department}}</td>
            <td>{{object.college_name}}</td>
            <td>{{object.rollnumber}}</td>
            <td>{{object.id}}</td>
                
            
           
          </tr>
         
        </tbody>
    </table>
    </table>
    <input type="submit" class = " btn btn-danger" style = "border-radius: 20px;" value="Confirm">
    <a type = "button" class="btn btn-success " href="{% url 'CSE:list' %}" style = "border-radius: 20px;">No</a>
    
</form>

{% endblock %}


NIE/templates/CBV/detail.html

{% extends 'basic.html' %}

{% block content %}
<h1>Student detail page.</h1>

<table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Department</th>
        <th scope="col">Roll.number</th>
        <th scope="col">College Name</th>
        <th scope="col">ID</th>
        
      </tr>
    </thead>
    <tbody>
       
      <tr>
        
        <td>{{object.name}}</td>
        <td>{{object.department}}</td>
        <td>{{object.rollnumber}}</td>
        <td>{{object.college_name}}</td>
        <td>{{object.id}}</td>
        
      </tr>
     
    </tbody>
  </table>

{% endblock %}


NIE/templates/CBV/forms.html

{% extends 'basic.html' %}

{% block content %}
<h1>Student Application form page.</h1>

<form action  = '', method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value = "Submit" class = "btn btn-success" style = "border-radius: 20px;"><br><br><br><br><br><br>
    
</form> 

{% endblock %}


NIE/templates/CBV/list.html

{% extends 'basic.html' %}

{% block content %}

<h1>Student List page.</h1><br>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Department</th>
        <th>Year</th>
        <th>Roll Number</th>
        <th>Details</th>
        <th>Update</th>
        <th>Delete</th>
        
        
    </tr>
    {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td>{{object.name}}</td>
                <td> {{object.department}}</td>
                <td>{{object.college_name}}</td>
                <td> {{object.rollnumber}} </td>  
                <td><a type="button" class="btn btn-primary" style="border-radius: 20px;" href= "{{object.id}}/detail">Detail</a></td>
                <td><a type=" button " class = "btn btn-success" style="border-radius: 20px;" href ="{{object.id}}/update" >Update</a></td>
                <td><a type = "button" class="btn btn-danger" style="border-radius: 20px;" href="{{object.id}}/delete">Delete</a></td>
                                      
            </tr>
            
    {% endfor %}

</table>

{% endblock %}

NIE/templates/CBV/update.html

{% extends 'basic.html' %}

{% block content %}
<h1>Student Update page.</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class = "button" value="Save">   
    
</form>


{% endblock %}


NIE/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
{% comment %} navbar {% endcomment %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'CSE:index'%}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url'CSE:products'%}">Products</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:service'%}">Service</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:contacts'%}">Contacts</a>
          </li>

          <li class="nav-item"></li>
            <a class="nav-link" href="{% url 'CSE:studentList'%}">Students</a>
          </li>
          
                      
      </div>
    </div>
  </nav>

{% block content %}
{% endblock %}


</body>
</html>

NIE/templates/basic1.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Service</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Contacts</a>
              </li>
              
                          
          </div>
        </div>
      </nav>
  <!-- navbar -->
   <!-- buttons -->
    <button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-secondary">Secondary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-warning">Warning</button>
<button type="button" class="btn btn-info">Info</button>
<button type="button" class="btn btn-light">Light</button>
<button type="button" class="btn btn-dark">Dark</button>

<button type="button" class="btn btn-link">Link</button>

<!-- dropdowns -->
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

NIE/templates/contacts.html
{% extends 'basic.html'%}
{% block content %}
<h1>this is a contacts page.</h1>
{% endblock %}

NIE/templates/index.html
{% extends 'basic.html'%}
{% block content %}
<h1>Welcome to web development</h1>
{% endblock %}

NIE/templates/products.html
{% extends 'basic.html'%}

{% block content %}
<h1>Products page</h1>
Name :{{name}}<br>
College name :{{c_name}}<br>
Department name :{{d_name}}<br>
Roll number :{{r_number}}<br>

{% endblock %}

NIE/templates/service.html
{% extends 'basic.html'%}
{% block content %}
<h1>this is a service page.</h1>
{% endblock %}

NIE/templates/studentList.html
{% extends 'basic.html'%}

{% include "basic.html" %}

 {% block content %}

 {% for student in students %}
 
 Name:{{student.name}}<br>
 Department: {{student.department}}<br>
 College Name: {{student.college_name}}<br>
 Roll number: {{student.rollnumber}}<br>
 <hr>



 {% endfor %}
 
 {% endblock %}
 